name: Generate Snake

on:
  schedule: # Run workflow automatically
    - cron: "0 22 * * *" # Every day at 22:00 UTC
  push: # Run workflow on push
    branches:
      - master # or main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: dist/github-contribution-grid-snake.svg
          message: "Generated snake animation"
          push: true
